# Generated by Django 5.1.1 on 2024-10-05 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koerailm_weather_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='favouriteplace',
            old_name='place_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='folksaying',
            old_name='folk_saying',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='feedback_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='folksaying',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
